#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
if "$(dirname "$0")/stest" -dqr -n "$cache" $PATH; then
	"$(dirname "$0")/stest" -flx $PATH | sort -u | tee "$cache"
else
	cat "$cache"
fi
